"""Bootstrap entity definitions - hundreds of Hindu mythology entities."""

from __future__ import annotations

from purana_factory.database.base import EntityType

# Format: (name, entity_type, sanskrit_name or None)
BOOTSTRAP_ENTITIES: list[tuple[str, EntityType, str | None]] = [
    # Trimurti and consorts
    ("Shiva", EntityType.DEITY, "शिव"),
    ("Parvati", EntityType.DEITY, "पार्वती"),
    ("Ganesha", EntityType.DEITY, "गणेश"),
    ("Kartikeya", EntityType.DEITY, "कार्तिकेय"),
    ("Nandi", EntityType.ANIMAL, "नन्दि"),
    ("Vishnu", EntityType.DEITY, "विष्णु"),
    ("Lakshmi", EntityType.DEITY, "लक्ष्मी"),
    ("Brahma", EntityType.DEITY, "ब्रह्मा"),
    ("Saraswati", EntityType.DEITY, "सरस्वती"),
    # Ramayana
    ("Rama", EntityType.AVATAR, "राम"),
    ("Sita", EntityType.CHARACTER, "सीता"),
    ("Lakshmana", EntityType.CHARACTER, "लक्ष्मण"),
    ("Hanuman", EntityType.CHARACTER, "हनुमान"),
    ("Ravana", EntityType.DEMON, "रावण"),
    ("Bharata", EntityType.CHARACTER, "भरत"),
    ("Shatrughna", EntityType.CHARACTER, "शत्रुघ्न"),
    ("Dasharatha", EntityType.KING, "दशरथ"),
    ("Kaushalya", EntityType.QUEEN, "कौशल्या"),
    ("Kaikeyi", EntityType.QUEEN, "कैकेयी"),
    ("Sumitra", EntityType.QUEEN, "सुमित्रा"),
    ("Jatayu", EntityType.ANIMAL, "जटायु"),
    ("Garuda", EntityType.ANIMAL, "गरुड"),
    ("Vali", EntityType.CHARACTER, "वालि"),
    ("Sugriva", EntityType.CHARACTER, "सुग्रीव"),
    ("Vibhishana", EntityType.CHARACTER, "विभीषण"),
    ("Kumbhakarna", EntityType.DEMON, "कुम्भकर्ण"),
    ("Indrajit", EntityType.CHARACTER, "इन्द्रजित"),
    ("Maricha", EntityType.DEMON, "मारीच"),
    ("Surpanakha", EntityType.DEMON, "शूर्पणखा"),
    # Mahabharata
    ("Krishna", EntityType.AVATAR, "कृष्ण"),
    ("Radha", EntityType.CHARACTER, "राधा"),
    ("Arjuna", EntityType.CHARACTER, "अर्जुन"),
    ("Bhishma", EntityType.CHARACTER, "भीष्म"),
    ("Karna", EntityType.CHARACTER, "कर्ण"),
    ("Draupadi", EntityType.CHARACTER, "द्रौपदी"),
    ("Yudhishthira", EntityType.KING, "युधिष्ठिर"),
    ("Bhima", EntityType.CHARACTER, "भीम"),
    ("Nakula", EntityType.CHARACTER, "नकुल"),
    ("Sahadeva", EntityType.CHARACTER, "सहदेव"),
    ("Duryodhana", EntityType.CHARACTER, "दुर्योधन"),
    ("Dushasana", EntityType.CHARACTER, "दुःशासन"),
    ("Kunti", EntityType.CHARACTER, "कुन्ती"),
    ("Gandhari", EntityType.QUEEN, "गान्धारी"),
    ("Dhritarashtra", EntityType.KING, "धृतराष्ट्र"),
    ("Vidura", EntityType.CHARACTER, "विदुर"),
    ("Shakuni", EntityType.CHARACTER, "शकुनि"),
    ("Abhimanyu", EntityType.CHARACTER, "अभिमन्यु"),
    ("Parikshit", EntityType.KING, "परीक्षित"),
    ("Ashwatthama", EntityType.CHARACTER, "अश्वत्थामा"),
    ("Drona", EntityType.SAGE, "द्रोण"),
    ("Ekalavya", EntityType.CHARACTER, "एकलव्य"),
    ("Shalya", EntityType.KING, "शल्य"),
    ("Jayadratha", EntityType.KING, "जयद्रथ"),
    ("Ghatotkacha", EntityType.CHARACTER, "घटोत्कच"),
    ("Balarama", EntityType.AVATAR, "बलराम"),
    ("Subhadra", EntityType.CHARACTER, "सुभद्रा"),
    ("Rukmini", EntityType.QUEEN, "रुक्मिणी"),
    ("Satyabhama", EntityType.QUEEN, "सत्यभामा"),
    ("Jarasandha", EntityType.KING, "जरासन्ध"),
    ("Shishupala", EntityType.KING, "शिशुपाल"),
    # Devi
    ("Durga", EntityType.DEITY, "दुर्गा"),
    ("Kali", EntityType.DEITY, "काली"),
    ("Lalita", EntityType.DEITY, "ललिता"),
    ("Chamunda", EntityType.DEITY, "चामुण्डा"),
    ("Annapurna", EntityType.DEITY, "अन्नपूर्णा"),
    ("Kamakhya", EntityType.DEITY, "कामाख्या"),
    ("Meenakshi", EntityType.DEITY, "मीनाक्षी"),
    ("Amba", EntityType.DEITY, "अम्बा"),
    # Vedic deities
    ("Indra", EntityType.DEITY, "इन्द्र"),
    ("Agni", EntityType.DEITY, "अग्नि"),
    ("Varuna", EntityType.DEITY, "वरुण"),
    ("Yama", EntityType.DEITY, "यम"),
    ("Kubera", EntityType.DEITY, "कुबेर"),
    ("Surya", EntityType.DEITY, "सूर्य"),
    ("Chandra", EntityType.DEITY, "चन्द्र"),
    ("Vayu", EntityType.DEITY, "वायु"),
    ("Soma", EntityType.DEITY, "सोम"),
    ("Mitra", EntityType.DEITY, "मित्र"),
    ("Pushan", EntityType.DEITY, "पूषन्"),
    ("Ashvins", EntityType.DEITY, "अश्विनौ"),
    ("Rudra", EntityType.DEITY, "रुद्र"),
    ("Prajapati", EntityType.DEITY, "प्रजापति"),
    # Sages and rishis
    ("Narada", EntityType.SAGE, "नारद"),
    ("Vasishta", EntityType.RISHI, "वसिष्ठ"),
    ("Vishwamitra", EntityType.RISHI, "विश्वामित्र"),
    ("Brihaspati", EntityType.SAGE, "बृहस्पति"),
    ("Shukracharya", EntityType.SAGE, "शुक्राचार्य"),
    ("Markandeya", EntityType.SAGE, "मार्कण्डेय"),
    ("Agastya", EntityType.RISHI, "अगस्त्य"),
    ("Valmiki", EntityType.SAGE, "वाल्मीकि"),
    ("Vyasa", EntityType.SAGE, "व्यास"),
    ("Shandilya", EntityType.RISHI, "शाण्डिल्य"),
    ("Gautama", EntityType.RISHI, "गौतम"),
    ("Atri", EntityType.RISHI, "अत्रि"),
    ("Bhrigu", EntityType.RISHI, "भृगु"),
    ("Angiras", EntityType.RISHI, "अङ्गिरस"),
    ("Pulastya", EntityType.RISHI, "पुलस्त्य"),
    ("Pulaha", EntityType.RISHI, "पुलह"),
    ("Kratu", EntityType.RISHI, "क्रतु"),
    ("Jamadagni", EntityType.RISHI, "जमदग्नि"),
    ("Parashurama", EntityType.AVATAR, "परशुराम"),
    ("Durvasa", EntityType.SAGE, "दुर्वासा"),
    ("Chyavana", EntityType.SAGE, "च्यवन"),
    ("Kanva", EntityType.SAGE, "कण्व"),
    ("Shukadeva", EntityType.SAGE, "शुकदेव"),
    # Devotees and characters
    ("Prahlada", EntityType.CHARACTER, "प्रह्लाद"),
    ("Dhruva", EntityType.CHARACTER, "ध्रुव"),
    ("Ambarisha", EntityType.KING, "अम्बरीष"),
    ("Hiranyakashipu", EntityType.DEMON, "हिरण्यकशिपु"),
    ("Hiranyaksha", EntityType.DEMON, "हिरण्याक्ष"),
    ("Narasimha", EntityType.AVATAR, "नरसिंह"),
    ("Vamana", EntityType.AVATAR, "वामन"),
    ("Matsya", EntityType.AVATAR, "मत्स्य"),
    ("Kurma", EntityType.AVATAR, "कूर्म"),
    ("Varaha", EntityType.AVATAR, "वराह"),
    ("Buddha", EntityType.AVATAR, "बुद्ध"),
    ("Kalki", EntityType.AVATAR, "कल्कि"),
    # Asuras and demons
    ("Mahishasura", EntityType.ASURA, "महिषासुर"),
    ("Shumbha", EntityType.ASURA, "शुम्भ"),
    ("Nishumbha", EntityType.ASURA, "निशुम्भ"),
    ("Raktabija", EntityType.ASURA, "रक्तबीज"),
    ("Taraka", EntityType.ASURA, "तारक"),
    ("Banasura", EntityType.ASURA, "बाणासुर"),
    ("Vritra", EntityType.DEMON, "वृत्र"),
    ("Namuchi", EntityType.DEMON, "नमुचि"),
    ("Andhaka", EntityType.DEMON, "अन्धक"),
    ("Jalandhara", EntityType.DEMON, "जलन्धर"),
    # Weapons
    ("Sudarshana Chakra", EntityType.WEAPON, "सुदर्शन चक्र"),
    ("Trishula", EntityType.WEAPON, "त्रिशूल"),
    ("Pinaka", EntityType.WEAPON, "पिनाक"),
    ("Vajra", EntityType.WEAPON, "वज्र"),
    ("Pashupatastra", EntityType.WEAPON, "पाशुपतास्त्र"),
    ("Brahmastra", EntityType.WEAPON, "ब्रह्मास्त्र"),
    ("Narayanastra", EntityType.WEAPON, "नारायणास्त्र"),
    ("Gandiva", EntityType.WEAPON, "गाण्डीव"),
    ("Sharanga", EntityType.WEAPON, "शार्ङ्ग"),
    ("Kaumodaki", EntityType.WEAPON, "कौमोदकी"),
    ("Nandaka", EntityType.WEAPON, "नन्दक"),
    ("Khanda", EntityType.WEAPON, "खड्ग"),
    # Vehicles
    ("Nandi Bull", EntityType.VEHICLE, None),
    ("Garuda Vahana", EntityType.VEHICLE, None),
    ("Hamsa", EntityType.VEHICLE, "हंस"),
    ("Airavata", EntityType.ANIMAL, "ऐरावत"),
    ("Uchchaihshravas", EntityType.ANIMAL, "उच्चैःश्रवस्"),
    ("Makara", EntityType.ANIMAL, "मकर"),
    # Places
    ("Kailash", EntityType.MOUNTAIN, "कैलाश"),
    ("Himalaya", EntityType.MOUNTAIN, "हिमालय"),
    ("Meru", EntityType.MOUNTAIN, "मेरु"),
    ("Vindhya", EntityType.MOUNTAIN, "विन्ध्य"),
    ("Ganga", EntityType.RIVER, "गङ्गा"),
    ("Yamuna", EntityType.RIVER, "यमुना"),
    ("Saraswati River", EntityType.RIVER, "सरस्वती"),
    ("Narmada", EntityType.RIVER, "नर्मदा"),
    ("Godavari", EntityType.RIVER, "गोदावरी"),
    ("Kaveri", EntityType.RIVER, "कावेरी"),
    ("Krishna River", EntityType.RIVER, "कृष्णा"),
    ("Ayodhya", EntityType.PLACE, "अयोध्या"),
    ("Mathura", EntityType.PLACE, "मथुरा"),
    ("Vrindavan", EntityType.PLACE, "वृन्दावन"),
    ("Dwarka", EntityType.PLACE, "द्वारका"),
    ("Hastinapura", EntityType.PLACE, "हस्तिनापुर"),
    ("Indraprastha", EntityType.PLACE, "इन्द्रप्रस्थ"),
    ("Kurukshetra", EntityType.PLACE, "कुरुक्षेत्र"),
    ("Varanasi", EntityType.PLACE, "वाराणसी"),
    ("Haridwar", EntityType.PLACE, "हरिद्वार"),
    ("Rameswaram", EntityType.PLACE, "रामेश्वरम्"),
    ("Kanchipuram", EntityType.PLACE, "काञ्चीपुरम्"),
    ("Ujjain", EntityType.PLACE, "उज्जयिनी"),
    ("Puri", EntityType.PLACE, "पुरी"),
    ("Badarinath", EntityType.PLACE, "बदरिनाथ"),
    ("Kedarnath", EntityType.PLACE, "केदारनाथ"),
    ("Amarnath", EntityType.PLACE, "अमरनाथ"),
    ("Vaikuntha", EntityType.PLACE, "वैकुण्ठ"),
    ("Swarga", EntityType.PLACE, "स्वर्ग"),
    ("Patala", EntityType.PLACE, "पाताल"),
    ("Lanka", EntityType.KINGDOM, "लङ्का"),
    ("Magadha", EntityType.KINGDOM, "मगध"),
    ("Panchala", EntityType.KINGDOM, "पाञ्चाल"),
    ("Kosala", EntityType.KINGDOM, "कोसल"),
    ("Kalinga", EntityType.KINGDOM, "कलिङ्ग"),
    ("Matsya Kingdom", EntityType.KINGDOM, "मत्स्य"),
    ("Chedi", EntityType.KINGDOM, "चेदि"),
    ("Videha", EntityType.KINGDOM, "विदेह"),
    ("Solar Dynasty", EntityType.DYNASTY, "सूर्यवंश"),
    ("Lunar Dynasty", EntityType.DYNASTY, "चन्द्रवंश"),
    ("Yadu Dynasty", EntityType.DYNASTY, "यदुवंश"),
    # Festivals
    ("Diwali", EntityType.FESTIVAL, "दीपावली"),
    ("Navaratri", EntityType.FESTIVAL, "नवरात्रि"),
    ("Dussehra", EntityType.FESTIVAL, "दशहरा"),
    ("Holi", EntityType.FESTIVAL, "होली"),
    ("Maha Shivaratri", EntityType.FESTIVAL, "महाशिवरात्रि"),
    ("Janmashtami", EntityType.FESTIVAL, "जन्माष्टमी"),
    ("Rama Navami", EntityType.FESTIVAL, "रामनवमी"),
    ("Ganesh Chaturthi", EntityType.FESTIVAL, "गणेश चतुर्थी"),
    ("Onam", EntityType.FESTIVAL, "ओणम्"),
    ("Pongal", EntityType.FESTIVAL, "पोंगल"),
    ("Makar Sankranti", EntityType.FESTIVAL, "मकर संक्रान्ति"),
    ("Vasant Panchami", EntityType.FESTIVAL, "वसन्त पञ्चमी"),
    ("Karva Chauth", EntityType.FESTIVAL, "करवा चौथ"),
    ("Raksha Bandhan", EntityType.FESTIVAL, "रक्षा बन्धन"),
    # Temples
    ("Kashi Vishwanath", EntityType.TEMPLE, "काशी विश्वनाथ"),
    ("Somnath", EntityType.TEMPLE, "सोमनाथ"),
    ("Tirupati Balaji", EntityType.TEMPLE, "तिरुपति बालाजी"),
    ("Meenakshi Temple", EntityType.TEMPLE, "मीनाक्षी मन्दिर"),
    ("Jagannath Temple", EntityType.TEMPLE, "जगन्नाथ मन्दिर"),
    ("Kedarnath Temple", EntityType.TEMPLE, "केदारनाथ मन्दिर"),
    ("Brihadeeswarar Temple", EntityType.TEMPLE, "बृहदीश्वर मन्दिर"),
    ("Khajuraho", EntityType.TEMPLE, "खजुराहो"),
    ("Konark Sun Temple", EntityType.TEMPLE, "कोणार्क सूर्य मन्दिर"),
    ("Akshardham", EntityType.TEMPLE, "अक्षरधाम"),
    # Scriptures
    ("Mahabharata", EntityType.SCRIPTURE, "महाभारत"),
    ("Ramayana", EntityType.SCRIPTURE, "रामायण"),
    ("Bhagavata Purana", EntityType.SCRIPTURE, "भागवत पुराण"),
    ("Shiva Purana", EntityType.SCRIPTURE, "शिव पुराण"),
    ("Vishnu Purana", EntityType.SCRIPTURE, "विष्णु पुराण"),
    ("Devi Bhagavatam", EntityType.SCRIPTURE, "देवी भागवत"),
    ("Skanda Purana", EntityType.SCRIPTURE, "स्कन्द पुराण"),
    ("Markandeya Purana", EntityType.SCRIPTURE, "मार्कण्डेय पुराण"),
    ("Padma Purana", EntityType.SCRIPTURE, "पद्म पुराण"),
    ("Garuda Purana", EntityType.SCRIPTURE, "गरुड पुराण"),
    ("Narada Purana", EntityType.SCRIPTURE, "नारद पुराण"),
    ("Rigveda", EntityType.SCRIPTURE, "ऋग्वेद"),
    ("Yajurveda", EntityType.SCRIPTURE, "यजुर्वेद"),
    ("Samaveda", EntityType.SCRIPTURE, "सामवेद"),
    ("Atharvaveda", EntityType.SCRIPTURE, "अथर्ववेद"),
    ("Bhagavad Gita", EntityType.SCRIPTURE, "भगवद्गीता"),
    ("Upanishads", EntityType.SCRIPTURE, "उपनिषद्"),
    # Concepts
    ("Dharma", EntityType.CONCEPT, "धर्म"),
    ("Karma", EntityType.CONCEPT, "कर्म"),
    ("Moksha", EntityType.CONCEPT, "मोक्ष"),
    ("Samsara", EntityType.CONCEPT, "संसार"),
    ("Maya", EntityType.CONCEPT, "माया"),
    ("Atman", EntityType.CONCEPT, "आत्मन्"),
    ("Brahman", EntityType.CONCEPT, "ब्रह्मन्"),
    ("Yoga", EntityType.CONCEPT, "योग"),
    ("Bhakti", EntityType.CONCEPT, "भक्ति"),
    ("Jnana", EntityType.CONCEPT, "ज्ञान"),
    ("Tapas", EntityType.CONCEPT, "तपस्"),
    ("Yajna", EntityType.CONCEPT, "यज्ञ"),
    ("Guru", EntityType.CONCEPT, "गुरु"),
    ("Avatar Concept", EntityType.CONCEPT, "अवतार"),
    ("Trimurti", EntityType.CONCEPT, "त्रिमूर्ति"),
    # Events
    ("Samudra Manthan", EntityType.EVENT, "समुद्र मन्थन"),
    ("Kurukshetra War", EntityType.EVENT, "कुरुक्षेत्र युद्ध"),
    ("Churning of Ocean", EntityType.EVENT, None),
    ("Burning of Khandava Forest", EntityType.EVENT, None),
    ("Swayamvara of Draupadi", EntityType.EVENT, None),
    ("Exile of Rama", EntityType.EVENT, None),
    ("Lifting of Govardhan", EntityType.EVENT, None),
    # Additional deities and characters
    ("Kamadeva", EntityType.DEITY, "कामदेव"),
    ("Rati", EntityType.DEITY, "रति"),
    ("Shani", EntityType.DEITY, "शनि"),
    ("Rahu", EntityType.DEITY, "राहु"),
    ("Ketu", EntityType.DEITY, "केतु"),
    ("Dhanvantari", EntityType.DEITY, "धन्वन्तरि"),
    ("Hayagriva", EntityType.AVATAR, "हयग्रीव"),
    ("Mohini", EntityType.AVATAR, "मोहिनी"),
    ("Tulsi", EntityType.CHARACTER, "तुलसी"),
    ("Sabari", EntityType.CHARACTER, "शबरी"),
    ("Ahalya", EntityType.CHARACTER, "अहल्या"),
    ("Mandodari", EntityType.QUEEN, "मन्दोदरी"),
    ("Tara", EntityType.QUEEN, "तारा"),
    ("Urmila", EntityType.CHARACTER, "ऊर्मिला"),
    ("Mandavi", EntityType.CHARACTER, "माण्डवी"),
    ("Shrutakirti", EntityType.CHARACTER, "श्रुतकीर्ति"),
    ("Shakuntala", EntityType.CHARACTER, "शकुन्तला"),
    ("Dushyanta", EntityType.KING, "दुष्यन्त"),
    ("Bharata Chakravartin", EntityType.KING, "भरत"),
    ("Harishchandra", EntityType.KING, "हरिश्चन्द्र"),
    ("Raghu", EntityType.KING, "रघु"),
    ("Ikshvaku", EntityType.KING, "इक्ष्वाकु"),
    ("Manu", EntityType.CHARACTER, "मनु"),
    ("Satyavati", EntityType.CHARACTER, "सत्यवती"),
    ("Ambika", EntityType.CHARACTER, "अम्बिका"),
    ("Ambalika", EntityType.CHARACTER, "अम्बालिका"),
    ("Urvashi", EntityType.CHARACTER, "उर्वशी"),
    ("Menaka", EntityType.CHARACTER, "मेनका"),
    ("Rambha", EntityType.CHARACTER, "रम्भा"),
    ("Tilottama", EntityType.CHARACTER, "तिलोत्तमा"),
    ("Apsaras", EntityType.CONCEPT, "अप्सरस्"),
    ("Gandharvas", EntityType.CONCEPT, "गन्धर्व"),
    ("Yakshas", EntityType.CONCEPT, "यक्ष"),
    ("Rakshasas", EntityType.CONCEPT, "राक्षस"),
    ("Nagas", EntityType.CONCEPT, "नाग"),
    ("Vasuki", EntityType.ANIMAL, "वासुकि"),
    ("Shesha", EntityType.ANIMAL, "शेष"),
    ("Ananta", EntityType.ANIMAL, "अनन्त"),
    ("Takshaka", EntityType.ANIMAL, "तक्षक"),
]
