"""initial_schema

Revision ID: 31facd208072
Revises: 
Create Date: 2026-06-21 17:20:00.752627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31facd208072'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.Enum('DEITY', 'CHARACTER', 'SAGE', 'RISHI', 'DEMON', 'ASURA', 'KING', 'QUEEN', 'DYNASTY', 'KINGDOM', 'TEMPLE', 'PLACE', 'MOUNTAIN', 'RIVER', 'WEAPON', 'OBJECT', 'ANIMAL', 'VEHICLE', 'SCRIPTURE', 'FESTIVAL', 'EVENT', 'CONCEPT', 'AVATAR', name='entitytype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='entitystatus'), nullable=False),
    sa.Column('sanskrit_name', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity'))
    )
    op.create_index(op.f('ix_entity_entity_type'), 'entity', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entity_name'), 'entity', ['name'], unique=False)
    op.create_index(op.f('ix_entity_slug'), 'entity', ['slug'], unique=True)
    op.create_index(op.f('ix_entity_status'), 'entity', ['status'], unique=False)
    op.create_table('audio_asset',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('script', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], name=op.f('fk_audio_asset_entity_id_entity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio_asset'))
    )
    op.create_index(op.f('ix_audio_asset_entity_id'), 'audio_asset', ['entity_id'], unique=False)
    op.create_table('concept',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('philosophical_context', sa.Text(), nullable=True),
    sa.Column('scriptural_basis', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], name=op.f('fk_concept_entity_id_entity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_concept'))
    )
    op.create_index(op.f('ix_concept_entity_id'), 'concept', ['entity_id'], unique=False)
    op.create_table('entity_content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('aliases', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('iconography', sa.Text(), nullable=True),
    sa.Column('powers', sa.Text(), nullable=True),
    sa.Column('abilities', sa.Text(), nullable=True),
    sa.Column('boons', sa.Text(), nullable=True),
    sa.Column('curses', sa.Text(), nullable=True),
    sa.Column('teachings', sa.Text(), nullable=True),
    sa.Column('virtues', sa.Text(), nullable=True),
    sa.Column('flaws', sa.Text(), nullable=True),
    sa.Column('moral_lessons', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], name=op.f('fk_entity_content_entity_id_entity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_content'))
    )
    op.create_index(op.f('ix_entity_content_entity_id'), 'entity_content', ['entity_id'], unique=False)
    op.create_table('entity_relationship',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_entity_id', sa.Integer(), nullable=False),
    sa.Column('target_entity_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.Enum('FATHER_OF', 'MOTHER_OF', 'CHILD_OF', 'CONSORT_OF', 'DISCIPLE_OF', 'GURU_OF', 'ALLY_OF', 'ENEMY_OF', 'AVATAR_OF', 'INCARNATION_OF', 'USES', 'RIDES', 'OWNS', 'RULES', 'RESIDES_AT', 'ASSOCIATED_WITH', 'PARTICIPATED_IN', 'WORSHIPPED_AT', name='relationshiptype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_tradition', sa.String(length=255), nullable=True),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entity.id'], name=op.f('fk_entity_relationship_source_entity_id_entity'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entity.id'], name=op.f('fk_entity_relationship_target_entity_id_entity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_relationship'))
    )
    op.create_index(op.f('ix_entity_relationship_source_entity_id'), 'entity_relationship', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_entity_relationship_target_entity_id'), 'entity_relationship', ['target_entity_id'], unique=False)
    op.create_table('festival',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rituals', sa.Text(), nullable=True),
    sa.Column('associated_deities', sa.Text(), nullable=True),
    sa.Column('calendar_info', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], name=op.f('fk_festival_entity_id_entity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_festival'))
    )
    op.create_index(op.f('ix_festival_entity_id'), 'festival', ['entity_id'], unique=False)
    op.create_table('generation_job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.Enum('ENTITY_PROFILE', 'RELATIONSHIPS', 'STORIES', 'TEMPLES', 'FESTIVALS', 'WEAPONS', 'PLACES', 'IMAGE_PROMPT', 'IMAGE_GENERATION', 'NARRATION_SCRIPT', 'AUDIO_GENERATION', 'TRANSLATION', 'VALIDATION', 'EXPORT', 'BOOTSTRAP', name='jobtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'RETRY', name='jobstatus'), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], name=op.f('fk_generation_job_entity_id_entity'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_job'))
    )
    op.create_index(op.f('ix_generation_job_entity_id'), 'generation_job', ['entity_id'], unique=False)
    op.create_index(op.f('ix_generation_job_job_type'), 'generation_job', ['job_type'], unique=False)
    op.create_index(op.f('ix_generation_job_status'), 'generation_job', ['status'], unique=False)
    op.create_table('image_asset',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('image_type', sa.Enum('PORTRAIT', 'TEMPLE', 'STORY', 'WEAPON', 'FESTIVAL', 'FAMILY_TREE', 'KNOWLEDGE_GRAPH', name='imagetype'), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('style', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], name=op.f('fk_image_asset_entity_id_entity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_image_asset'))
    )
    op.create_index(op.f('ix_image_asset_entity_id'), 'image_asset', ['entity_id'], unique=False)
    op.create_table('language_content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('source_language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], name=op.f('fk_language_content_entity_id_entity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_language_content'))
    )
    op.create_index(op.f('ix_language_content_entity_id'), 'language_content', ['entity_id'], unique=False)
    op.create_index(op.f('ix_language_content_language'), 'language_content', ['language'], unique=False)
    op.create_table('place',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('place_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('significance', sa.Text(), nullable=True),
    sa.Column('geography', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], name=op.f('fk_place_entity_id_entity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_place'))
    )
    op.create_index(op.f('ix_place_entity_id'), 'place', ['entity_id'], unique=False)
    op.create_table('search_keyword',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], name=op.f('fk_search_keyword_entity_id_entity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_keyword'))
    )
    op.create_index(op.f('ix_search_keyword_entity_id'), 'search_keyword', ['entity_id'], unique=False)
    op.create_index(op.f('ix_search_keyword_keyword'), 'search_keyword', ['keyword'], unique=False)
    op.create_table('source_reference',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('scripture', sa.String(length=255), nullable=False),
    sa.Column('citation', sa.Text(), nullable=True),
    sa.Column('tradition', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], name=op.f('fk_source_reference_entity_id_entity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_reference'))
    )
    op.create_index(op.f('ix_source_reference_entity_id'), 'source_reference', ['entity_id'], unique=False)
    op.create_table('story',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('full_narrative', sa.Text(), nullable=True),
    sa.Column('timeline', sa.Text(), nullable=True),
    sa.Column('lessons', sa.Text(), nullable=True),
    sa.Column('concepts', sa.Text(), nullable=True),
    sa.Column('scriptural_sources', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], name=op.f('fk_story_entity_id_entity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story'))
    )
    op.create_index(op.f('ix_story_entity_id'), 'story', ['entity_id'], unique=False)
    op.create_table('temple',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('location', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('significance', sa.Text(), nullable=True),
    sa.Column('pilgrimage_info', sa.Text(), nullable=True),
    sa.Column('associated_deities', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], name=op.f('fk_temple_entity_id_entity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_temple'))
    )
    op.create_index(op.f('ix_temple_entity_id'), 'temple', ['entity_id'], unique=False)
    op.create_table('weapon',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('history', sa.Text(), nullable=True),
    sa.Column('powers', sa.Text(), nullable=True),
    sa.Column('owners', sa.Text(), nullable=True),
    sa.Column('associated_stories', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], name=op.f('fk_weapon_entity_id_entity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weapon'))
    )
    op.create_index(op.f('ix_weapon_entity_id'), 'weapon', ['entity_id'], unique=False)
    op.create_table('generation_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['generation_job.id'], name=op.f('fk_generation_log_job_id_generation_job'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_log'))
    )
    op.create_index(op.f('ix_generation_log_job_id'), 'generation_log', ['job_id'], unique=False)
    op.create_table('story_variant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('tradition', sa.String(length=255), nullable=False),
    sa.Column('variant_title', sa.String(length=512), nullable=True),
    sa.Column('variant_narrative', sa.Text(), nullable=True),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], name=op.f('fk_story_variant_story_id_story'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story_variant'))
    )
    op.create_index(op.f('ix_story_variant_story_id'), 'story_variant', ['story_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_variant_story_id'), table_name='story_variant')
    op.drop_table('story_variant')
    op.drop_index(op.f('ix_generation_log_job_id'), table_name='generation_log')
    op.drop_table('generation_log')
    op.drop_index(op.f('ix_weapon_entity_id'), table_name='weapon')
    op.drop_table('weapon')
    op.drop_index(op.f('ix_temple_entity_id'), table_name='temple')
    op.drop_table('temple')
    op.drop_index(op.f('ix_story_entity_id'), table_name='story')
    op.drop_table('story')
    op.drop_index(op.f('ix_source_reference_entity_id'), table_name='source_reference')
    op.drop_table('source_reference')
    op.drop_index(op.f('ix_search_keyword_keyword'), table_name='search_keyword')
    op.drop_index(op.f('ix_search_keyword_entity_id'), table_name='search_keyword')
    op.drop_table('search_keyword')
    op.drop_index(op.f('ix_place_entity_id'), table_name='place')
    op.drop_table('place')
    op.drop_index(op.f('ix_language_content_language'), table_name='language_content')
    op.drop_index(op.f('ix_language_content_entity_id'), table_name='language_content')
    op.drop_table('language_content')
    op.drop_index(op.f('ix_image_asset_entity_id'), table_name='image_asset')
    op.drop_table('image_asset')
    op.drop_index(op.f('ix_generation_job_status'), table_name='generation_job')
    op.drop_index(op.f('ix_generation_job_job_type'), table_name='generation_job')
    op.drop_index(op.f('ix_generation_job_entity_id'), table_name='generation_job')
    op.drop_table('generation_job')
    op.drop_index(op.f('ix_festival_entity_id'), table_name='festival')
    op.drop_table('festival')
    op.drop_index(op.f('ix_entity_relationship_target_entity_id'), table_name='entity_relationship')
    op.drop_index(op.f('ix_entity_relationship_source_entity_id'), table_name='entity_relationship')
    op.drop_table('entity_relationship')
    op.drop_index(op.f('ix_entity_content_entity_id'), table_name='entity_content')
    op.drop_table('entity_content')
    op.drop_index(op.f('ix_concept_entity_id'), table_name='concept')
    op.drop_table('concept')
    op.drop_index(op.f('ix_audio_asset_entity_id'), table_name='audio_asset')
    op.drop_table('audio_asset')
    op.drop_index(op.f('ix_entity_status'), table_name='entity')
    op.drop_index(op.f('ix_entity_slug'), table_name='entity')
    op.drop_index(op.f('ix_entity_name'), table_name='entity')
    op.drop_index(op.f('ix_entity_entity_type'), table_name='entity')
    op.drop_table('entity')
    # ### end Alembic commands ###
